### ISSUE TITLE
Improve management of blank properties in application.yaml

### ISSUE THREAD

**Issue by Nheverest** [seedstack/jms-addon#11]
jms-addon uses Java Properties object to store vendor-specific properties. 
If some of these properties are declared but left blank in application.yaml, this can result in NullPointerException's at application startup, without much information for analysis. 

Object of this issue is to improve application behaviour in this case (use HashMap instead of Properties, trigger a warning if mandatory values are empty...). 

Sample configuration to reproduce the error (tested with Seedstack 19.11):
```
jms:
  connectionFactories:
    gnomeActiveMQConnectionFactory:
      vendorClass: org.apache.activemq.ActiveMQConnectionFactory
      vendorProperties:
        brokerURL: 
```
